version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-db-ctn
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_net

  redis:
    image: redis
    container_name: redis-cache-ctn
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_net

  springboot-1: &springboot-1
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: springboot-1
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - redis
    networks:
      - app_net

  springboot-2:
    <<: *springboot-1
    container_name: springboot-2

  springboot-3:
    <<: *springboot-1
    container_name: springboot-3

  nginx:
    image: nginx
    container_name: nginx-app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - springboot-1
      - springboot-2
      - springboot-3
    networks:
      - app_net

volumes:
  mysql_data:
  redis_data:

networks:
  app_net:
    driver: bridge
